import "./global.scss";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    // absolute: "", // this absolute title will overwrite all title from current layout metadata
    // but if you have metadata  on page level it will overwrite metadata from current layout
    default: "some default title",
    template: "%s | Rest of template title",
    absolute: "Absolute main title",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-svh">
        <header className="bg-blue-950 p-5 w-full fixed top-0 left-0 right-0 text-white">
          header
        </header>
        <main className="py-24 px-5 h-svh">{children}</main>
        <footer className="bg-blue-400 p-5 w-full fixed bottom-0 left-0 right-0">
          footer
        </footer>
      </body>
    </html>
  );
}
