import { Metadata } from "next";
import Link from "next/link";
import "./global.scss";
import MainNavbar from "../components/MainNavbar";

export const metadata: Metadata = {
  title: {
    // absolute: "", // this absolute title will overwrite all title from current layout metadata
    // but if you have metadata  on page level it will overwrite metadata from current layout
    default: "some default title",
    template: "%s | Rest of template title",
    absolute: "Absolute main title",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="m-0 h-full overflow-hidden">
      <body className="m-0 h-full overflow-hidden flex flex-col">
        <header className="bg-blue-950 p-5 w-full text-white">
          <Link href="/">
            <h1 className="py-5">Home</h1>
          </Link>

          <nav className="flex gap-5">
            <MainNavbar />
          </nav>
        </header>
        <main className="flex-1 overflow-auto">{children}</main>
        <footer className="bg-blue-400 p-5 w-full">footer</footer>
      </body>
    </html>
  );
}
